Added exit status check for mount command

diff --git a/field_file_system/usr/lib/bowerbird/beagleboard/bin/move_data_to_external b/field_file_system/usr/lib/bowerbird/beagleboard/bin/move_data_to_external
--- a/field_file_system/usr/lib/bowerbird/beagleboard/bin/move_data_to_external
+++ b/field_file_system/usr/lib/bowerbird/beagleboard/bin/move_data_to_external
@@ -6,7 +6,7 @@ DEBUG=false
 LOGGER=/usr/bin/logger
 VARIABLES_FILE=/etc/bowerbird/config/global_variables
 rsync_attempts=5 # default
-external_power=false # default
+external_power=true # default
 external_power_settle_time=15 # seconds
 
 if $DEBUG
@@ -98,7 +98,11 @@ then
 	if [ "$needs_mount" ]
 	then
 		$DPRINT mounting $mount_point
-		mount $mount_point
+		if ! mount $mount_point
+		then
+			echo "Couldn't mount external device ($mount_point)" > /dev/stderr
+			exit 1;
+		fi
 	fi
 fi
 
@@ -162,7 +166,7 @@ if $external_power
 then
 	# power down the hub, and the drive
 	# TODO don't power down the hub if someone else is using it
-	$DPRINT powering down the usb device and hub
+	$DPRINT powering down the usb device #and hub
 	set_power off usbhd
-	set_power off usbhub
+	#set_power off usbhub
 fi
